version: '3'
services:
  api:
    build:
      context: .
      dockerfile: python/Dockerfile
    environment:
      - FRONT_URL=http://frontend:3000
    ports:
      - "9000:9000"
  frontend:
    build:
      context: ./typescript
      dockerfile: simple-mercari-web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:9000


